pub(crate) const DELTAVA_AUTH_MESSAGE_PREFIX: &str = "__FLIGHT_PLANNER_DVA_AUTH__";
pub(crate) const DELTAVA_DEBUG_MESSAGE_PREFIX: &str = "__FLIGHT_PLANNER_SYNC_DEBUG__";
pub(crate) const DELTAVA_SYNC_RESULT_MESSAGE_PREFIX: &str = "__FLIGHT_PLANNER_SYNC_RESULT__";
pub(crate) const DELTAVA_LOGBOOK_REFRESH_RESULT_MESSAGE_PREFIX: &str =
    "__FLIGHT_PLANNER_LOGBOOK_REFRESH_RESULT__";
pub(crate) const DELTAVA_XML_MESSAGE_PREFIX: &str = "__FLIGHT_PLANNER_PFPX_XML__";
